name: Lint-code

on: push

jobs:
    lint:
        runs-on: ubuntu-latest
        container: node:20
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
              with: 
                node-version: 20

            - name: Install packages
              run: npm ci

            - name: Run linter
              run: npm run lint